import { Case } from "@/types";

export const MOCK_CASES: Case[] = [
  {
    id: "c1",
    title: "不動産ポータルサイトのSEO強化による自然流入3倍化",
    client_name: "株式会社ハウスナビ",
    industry: "不動産",
    services: ["SEO", "コンテンツ制作"],
    summary: "競合ひしめく不動産業界でドメイン評価を高め、主要KWで1位を獲得。月間オーガニック流入を6万から18万に増加させた。",
    background: "自社メディアへの流入がほぼ広告依存。SEO対策ゼロの状態から内製チームと連携して着手。",
    strategy: "E-E-A-Tを意識した専門性コンテンツを月10本制作。内部リンク最適化・構造化データ追加・Core Web Vitals改善を並行実施。",
    result: "大幅改善",
    kpi: "オーガニック流入 +200%・問い合わせCV +45%",
    period: "2023-09 〜 2024-08",
    tags: ["SEO", "コンテンツ", "不動産", "E-E-A-T", "内部リンク"],
    created_at: "2024-09-01",
  },
  {
    id: "c2",
    title: "EC通販のリスティング広告ROASを1.8倍に改善",
    client_name: "ビューティーモール株式会社",
    industry: "EC・通販",
    services: ["リスティング広告"],
    summary: "化粧品ECサイトの広告費を維持しながらROASを120%から220%に改善。商品カテゴリー別入札戦略を導入。",
    background: "広告費月200万円を投下していたが成果が頭打ち。競合との差別化ができていなかった。",
    strategy: "SKAGからCSAGへ構造を移行。除外KW2000件の精査・スマートビディング導入・広告文ABテストを月次で実施。",
    result: "大幅改善",
    kpi: "ROAS +83%・CPA -31%",
    period: "2024-01 〜 2024-12",
    tags: ["リスティング", "EC", "ROAS", "スマートビディング", "除外KW"],
    created_at: "2025-01-10",
  },
  {
    id: "c3",
    title: "学習塾チェーンのSNS運用で生徒獲得数を1.5倍に",
    client_name: "まなびの杜グループ",
    industry: "教育",
    services: ["SNS運用", "コンテンツ制作"],
    summary: "Instagram・TikTokを活用した保護者向けコンテンツ戦略で問い合わせ数を月30件から45件に引き上げた。",
    background: "競合塾がSNSに力を入れ始め、差別化が急務。自社での運用ナレッジがなかった。",
    strategy: "保護者が「子どもに見せたい」と思うコンテンツ設計。先生の授業風景・生徒の合格体験談をリール形式で展開。",
    result: "改善",
    kpi: "問い合わせ数 +50%・フォロワー 3,200→11,000",
    period: "2024-04 〜 2025-03",
    tags: ["SNS", "Instagram", "TikTok", "教育", "リール"],
    created_at: "2025-04-01",
  },
  {
    id: "c4",
    title: "BtoB製造業のMAツール導入でリード育成を自動化",
    client_name: "三和プレシジョン株式会社",
    industry: "BtoB製造",
    services: ["CRM"],
    summary: "Salesforce + Marketing Cloud導入により、展示会リードのナーチャリングを自動化。商談化率を8%から19%に向上。",
    background: "展示会で年間500件のリードを獲得するも、フォローアップが属人的で商談化できていなかった。",
    strategy: "リードスコアリング設計・メールシナリオ7本作成・Salesforceカスタマイズ・インサイドセールスチームとの連携体制構築。",
    result: "大幅改善",
    kpi: "商談化率 +138%・営業工数 -40%",
    period: "2023-06 〜 2024-03",
    tags: ["MA", "CRM", "BtoB", "Salesforce", "ナーチャリング", "リードスコアリング"],
    created_at: "2024-04-15",
  },
  {
    id: "c5",
    title: "美容クリニックのMEO対策＋口コミ施策でWeb予約を倍増",
    client_name: "スキンケアクリニック銀座",
    industry: "美容・健康",
    services: ["SEO", "コンテンツ制作"],
    summary: "Googleビジネスプロフィール最適化と口コミ促進施策を組み合わせ、Web予約数を月80件から165件に増加。",
    background: "新規開院から1年。認知が取れず予約が口コミ・紹介経由のみだった。",
    strategy: "MEO対策（写真・Q&A・投稿機能の活用）・施術後のフォローメールに口コミ誘導を挿入・FAQページをSEOに最適化。",
    result: "大幅改善",
    kpi: "Web予約 +106%・Googleマップ順位 圏外→3位",
    period: "2024-07 〜 2025-03",
    tags: ["MEO", "口コミ", "美容", "クリニック", "Googleビジネス"],
    created_at: "2025-04-20",
  },
  {
    id: "c6",
    title: "飲食チェーンのブランディング刷新でLTV向上",
    client_name: "カフェドリーム株式会社",
    industry: "飲食",
    services: ["ブランディング", "SNS運用", "動画制作"],
    summary: "ブランドコンセプトを「日常の特別」に再定義。動画広告・SNS・店舗POPの統合展開でリピート率が12pt向上。",
    background: "類似コンセプトのカフェが増加し差別化が困難に。価格競争に巻き込まれつつあった。",
    strategy: "競合調査・ターゲットインタビューからブランドコンセプトを策定。Instagram Reels+YouTube Shortsで世界観を一貫して発信。",
    result: "改善",
    kpi: "リピート率 +12pt・SNSフォロワー 5倍",
    period: "2024-02 〜 2025-01",
    tags: ["ブランディング", "動画", "飲食", "リピート", "SNS"],
    created_at: "2025-02-01",
  },
  {
    id: "c7",
    title: "金融系SaaSのコンテンツマーケで月次リード50件増",
    client_name: "ファイナンシャルクラウド株式会社",
    industry: "金融",
    services: ["SEO", "コンテンツ制作", "リスティング広告"],
    summary: "会計・経理担当者向けのハウツーコンテンツをSEO×広告で展開。月次オーガニックリードを0から50件に。",
    background: "競合SaaSに対してブランド認知が弱く、指名検索がほぼゼロ。",
    strategy: "ペルソナ（経理担当者）の検索意図を深掘り・比較記事・無料テンプレート訴求・ホワイトペーパーLPを制作。",
    result: "大幅改善",
    kpi: "月次リード +50件・指名検索数 +340%",
    period: "2023-10 〜 2024-09",
    tags: ["コンテンツ", "SaaS", "金融", "ホワイトペーパー", "指名検索"],
    created_at: "2024-10-01",
  },
];
