import { Case } from "@/types";

// ソース: di-kb / company/01_business/cases.md + services.md
export const MOCK_CASES: Case[] = [
  // ── 広告 ──────────────────────────────────────────────
  {
    id: "c01",
    title: "Facebook広告リード獲得ABテスト・LP改善で獲得効率6倍",
    client_name: "ソニーネットワークコミュニケーションズ",
    industry: "通信・IT",
    services: ["運用型広告", "CRO・LPO"],
    summary: "Facebook広告のリード獲得施策においてABテストとLP改善を組み合わせ、獲得効率を6倍に改善した。",
    background: "リード獲得広告の効率が伸び悩んでおり、クリエイティブとLPの最適化が急務だった。",
    strategy: "ターゲットセグメント別にABテストを設計し、勝ちパターンを高速で横展開。同時にLPのファーストビュー・CTAを改修。",
    result: "大幅改善",
    kpi: "獲得効率 6倍",
    period: "2023年〜",
    tags: ["Facebook広告", "ABテスト", "LPO", "リード獲得", "BtoC"],
    created_at: "2024-01-01",
  },
  {
    id: "c02",
    title: "広告運用×クリエイティブPDCA×MAでCPO昨対比41%削減",
    client_name: "リロバケーションズ",
    industry: "旅行・ホテル",
    services: ["運用型広告", "MA", "クリエイティブ制作"],
    summary: "広告運用・クリエイティブの高速PDCA・MAを連動させ、CPOを前年比41%削減することに成功した。",
    background: "広告費は一定規模を維持しているが、CPOが高止まりしており改善が必要だった。",
    strategy: "媒体横断でのCPA管理・週次クリエイティブ入れ替えサイクル・MAによるリード育成を三位一体で設計。",
    result: "大幅改善",
    kpi: "CPO 昨対比41%削減",
    period: "2022年〜",
    tags: ["広告運用", "CPO", "クリエイティブ", "MA", "旅行"],
    created_at: "2023-04-01",
  },
  {
    id: "c03",
    title: "Pinterest広告運用で他媒体比CPA 50%抑制",
    client_name: "（EC系・非公開）",
    industry: "EC・通販",
    services: ["運用型広告"],
    summary: "Pinterest広告を主軸に運用し、他媒体と比較してCPAを50%抑制。同媒体の特性を最大限活用した。",
    background: "既存媒体のCPAが高く、新たな獲得チャネルの開拓が課題だった。",
    strategy: "ピン画像のデザインガイドライン策定・ターゲティング設計・入札最適化を一気通貫で実施。",
    result: "大幅改善",
    kpi: "他媒体比CPA 50%抑制",
    period: "2024年〜",
    tags: ["Pinterest広告", "CPA", "EC", "新規チャネル"],
    created_at: "2024-03-01",
  },
  {
    id: "c04",
    title: "バナークリエイティブ改善でCTR 120%成果改善",
    client_name: "（広告主・非公開）",
    industry: "その他",
    services: ["クリエイティブ制作", "運用型広告"],
    summary: "バナークリエイティブの設計・改善施策によりCTRを約120%改善した。",
    background: "広告配信自体は順調だが、クリエイティブのCTRが伸び悩んでいた。",
    strategy: "ファーストビューのビジュアル訴求・コピー変更・サイズ別最適化を実施しABテストで検証。",
    result: "大幅改善",
    kpi: "CTR 約120%成果改善",
    period: "2023年〜",
    tags: ["バナー", "クリエイティブ", "CTR", "ABテスト"],
    created_at: "2023-07-01",
  },

  // ── SEO・コンテンツ ──────────────────────────────────
  {
    id: "c05",
    title: "SEO×コンテンツマーケで広告換算約632万円/月の自然検索流入を実現",
    client_name: "大手銀行",
    industry: "金融・保険",
    services: ["SEO", "コンテンツマーケティング"],
    summary: "SEOとコンテンツマーケティングを組み合わせ、月間自然検索流入を広告換算約632万円相当まで引き上げた。",
    background: "有料広告依存の集客構造から脱却し、オーガニック流入を収益柱に育てることが課題だった。",
    strategy: "E-E-A-T重視の専門コンテンツを設計・大量制作。内部リンク最適化と技術的SEOを並行実施。",
    result: "大幅改善",
    kpi: "広告換算 約632万円/月の自然検索流入",
    period: "2022年〜",
    tags: ["SEO", "コンテンツ", "金融", "オーガニック", "E-E-A-T"],
    created_at: "2023-01-01",
  },
  {
    id: "c06",
    title: "コンテンツ戦略・内部最適化で確定拠出年金KW 1位・流入437%UP",
    client_name: "大手金融機関",
    industry: "金融・保険",
    services: ["SEO", "コンテンツマーケティング"],
    summary: "確定拠出年金関連KWで1位を獲得し、流入を437%増加。金融特有の専門性・信頼性訴求を徹底した。",
    background: "確定拠出年金ページの検索順位が低く、競合メディアに流入を奪われていた。",
    strategy: "KW設計・コンテンツリライト・構造化データ追加・専門家監修コンテンツによる信頼性強化。",
    result: "大幅改善",
    kpi: "確定拠出年金KW 1位・流入 437%UP",
    period: "2022年〜",
    tags: ["SEO", "金融", "確定拠出年金", "流入増加", "専門コンテンツ"],
    created_at: "2022-10-01",
  },
  {
    id: "c07",
    title: "3ヶ月500本のコンテンツ制作でセッション20倍",
    client_name: "BtoB SaaS企業",
    industry: "BtoB・SaaS",
    services: ["コンテンツマーケティング", "SEO"],
    summary: "3ヶ月で500本のコンテンツを制作・公開し、サイト全体のセッションを20倍に引き上げた。",
    background: "新規立ち上げのオウンドメディアで認知がゼロに近く、早期のトラフィック獲得が必要だった。",
    strategy: "ターゲットKWを網羅的に設計し、SEO記事を高速量産。内部リンク設計も同時に整備。",
    result: "大幅改善",
    kpi: "セッション 20倍",
    period: "2023年〜",
    tags: ["コンテンツ", "SaaS", "BtoB", "量産", "オウンドメディア"],
    created_at: "2023-06-01",
  },
  {
    id: "c08",
    title: "不動産情報サイトのSEO×コンテンツで流入10倍",
    client_name: "不動産情報サイト（非公開）",
    industry: "不動産",
    services: ["SEO", "コンテンツマーケティング"],
    summary: "不動産ポータルサイトにおいてSEOとコンテンツを組み合わせ、オーガニック流入を10倍に拡大した。",
    background: "競合ポータルに押されオーガニック流入が低迷。SEO対策がほぼ未着手の状態だった。",
    strategy: "エリア×物件種別のKW設計・内部リンク最適化・Core Web Vitals改善・専門性の高いコラム制作。",
    result: "大幅改善",
    kpi: "オーガニック流入 10倍",
    period: "2022年〜",
    tags: ["SEO", "不動産", "コンテンツ", "流入増加", "ポータル"],
    created_at: "2022-08-01",
  },
  {
    id: "c09",
    title: "リニューアル後継続SEOコンサルで7ヶ月間に流入3.5倍",
    client_name: "一般財団法人（品質試験業）",
    industry: "BtoB・SaaS",
    services: ["SEO"],
    summary: "サイトリニューアル後にSEOコンサルを継続実施し、7ヶ月で流入を3.5倍に引き上げた。",
    background: "リニューアル直後はSEO評価がリセットされ、流入が大幅に減少していた。",
    strategy: "リニューアル時のリダイレクト設計・検索意図に合わせたコンテンツ修正・被リンク獲得施策を実施。",
    result: "大幅改善",
    kpi: "7ヶ月で流入 3.5倍",
    period: "2023年〜",
    tags: ["SEO", "リニューアル", "流入回復", "BtoB"],
    created_at: "2023-09-01",
  },
  {
    id: "c10",
    title: "三井住友銀行 Money Viva「新NISA 改悪」Google検索4位獲得",
    client_name: "三井住友銀行",
    industry: "金融・保険",
    services: ["コンテンツマーケティング", "SEO"],
    summary: "「新NISA 改悪」の検索需要急増に合わせて高速でコンテンツを制作・公開しGoogle 4位を獲得。",
    background: "時事性の高い金融KWに対してメディアと競合する形でのコンテンツ出稿が必要だった。",
    strategy: "トレンドKWのリアルタイム監視・コンテンツ企画から公開までのリードタイムを最短化。",
    result: "大幅改善",
    kpi: "「新NISA 改悪」Google検索 4位",
    period: "2024年〜",
    tags: ["コンテンツ", "SEO", "金融", "NISA", "時事対応"],
    created_at: "2024-02-01",
  },

  // ── Web制作・CRO ──────────────────────────────────────
  {
    id: "c11",
    title: "介護/不動産系サイトのUI改善で一覧ページ遷移率407%・見学予約404%改善",
    client_name: "（介護・不動産系・非公開）",
    industry: "不動産",
    services: ["CRO・LPO", "Web制作"],
    summary: "コラム上へのエリア検索機能追加などUI改善を実施し、一覧ページ遷移率407%・見学予約完了率404%改善を達成。",
    background: "コラムページへの流入は多いが一覧・詳細ページへの導線が弱くCV率が低かった。",
    strategy: "ユーザー行動分析からコンテンツページ上のCTA設計を改善。エリア検索UIをインライン配置。",
    result: "大幅改善",
    kpi: "一覧遷移率 407%・見学予約完了率 404%改善",
    period: "2023年〜",
    tags: ["CRO", "UI改善", "不動産", "導線設計", "CV率"],
    created_at: "2023-05-01",
  },
  {
    id: "c12",
    title: "住宅建築系LPファーストビュー改修でCVR約2.3倍・離脱率10%抑制",
    client_name: "住宅建築系（非公開）",
    industry: "不動産",
    services: ["CRO・LPO", "クリエイティブ制作"],
    summary: "LPのファーストビューをABテストで改修し、CVRを約2.3倍に改善。離脱率も約10%抑制した。",
    background: "広告流入は獲得できているが、LP到達後のCV率が低く費用対効果が悪化していた。",
    strategy: "ヒートマップ分析・ユーザーインタビュー結果をもとにFVコピーとビジュアルを複数パターンABテスト。",
    result: "大幅改善",
    kpi: "CVR 約2.3倍・離脱率 約10%抑制",
    period: "2023年〜",
    tags: ["LPO", "ABテスト", "住宅", "CVR", "ファーストビュー"],
    created_at: "2023-08-01",
  },
  {
    id: "c13",
    title: "BtoBクラウドサービスの月次LP改修でCVR 185%・CV数 193%",
    client_name: "BtoBクラウドサービス（非公開）",
    industry: "BtoB・SaaS",
    services: ["CRO・LPO"],
    summary: "月次でLPを継続改修し続けることでCVRを185%・CV数を193%に改善した。",
    background: "サービスLPへの流入は確保できているが、CVRが業界平均より低かった。",
    strategy: "毎月のデータ分析結果をもとにLP改修サイクルを確立。訴求軸の変更・フォーム改善・UI調整を繰り返す。",
    result: "大幅改善",
    kpi: "CVR 185%・CV数 193%",
    period: "2022年〜",
    tags: ["LPO", "BtoB", "SaaS", "CVR", "継続改善"],
    created_at: "2022-11-01",
  },
  {
    id: "c14",
    title: "BtoBサービスサイトリニューアルでCVR 155%・CV数 106%",
    client_name: "BtoBサービス企業（非公開）",
    industry: "BtoB・SaaS",
    services: ["Web制作", "CRO・LPO"],
    summary: "サービスサイトをフルリニューアルし、CVRを155%・CV数を106%に改善した。",
    background: "旧サイトは情報設計が古く、ユーザーが求める情報にたどり着けない構造だった。",
    strategy: "IA設計の見直し・ユーザー導線の再設計・デザインリニューアルを一気通貫で実施。",
    result: "改善",
    kpi: "CVR 155%・CV数 106%",
    period: "2023年〜",
    tags: ["Web制作", "リニューアル", "BtoB", "CVR", "UI/UX"],
    created_at: "2023-03-01",
  },

  // ── マーケティングDX・MA ──────────────────────────────
  {
    id: "c15",
    title: "エンゲージメント強化DX施策で売上前年比107.2%達成",
    client_name: "Sharing Innovations",
    industry: "BtoB・SaaS",
    services: ["MA", "DXコンサルティング"],
    summary: "マーケティングDX施策によるエンゲージメント強化を実施し、売上前年比107.2%を達成した。",
    background: "既存顧客のエンゲージメントが低下しており、リテンション強化が急務だった。",
    strategy: "MA導入・顧客行動データ統合・パーソナライズドコミュニケーション設計を実施。",
    result: "改善",
    kpi: "売上 前年比107.2%",
    period: "2023年〜",
    tags: ["DX", "MA", "エンゲージメント", "BtoB", "リテンション"],
    created_at: "2023-10-01",
  },
  {
    id: "c16",
    title: "不動産投資会社の資料請求後ナーチャリング改善で成約率大幅UP",
    client_name: "不動産投資会社（非公開）",
    industry: "不動産",
    services: ["MA", "DXコンサルティング"],
    summary: "資料請求後のナーチャリングフローをMA化・最適化し、成約率を大幅に向上させた。",
    background: "資料請求リードは月数百件あるが、その後のフォローが属人的で成約率が低かった。",
    strategy: "リードスコアリング設計・メールシナリオ構築・インサイドセールス連携フローを整備。",
    result: "大幅改善",
    kpi: "成約率 大幅UP",
    period: "2023年〜",
    tags: ["MA", "ナーチャリング", "不動産投資", "リードスコアリング"],
    created_at: "2023-11-01",
  },

  // ── SNS・PR ───────────────────────────────────────────
  {
    id: "c17",
    title: "旅行会社のデジタルマーケ支援でソーシャル358%成長",
    client_name: "日本国際旅行",
    industry: "旅行・ホテル",
    services: ["SNS運用", "運用型広告", "SEO"],
    summary: "広告・SEO・SNSを統合したデジタルマーケティング支援でSNSフォロワー・エンゲージメントが358%成長。",
    background: "オフライン中心のマーケティングからデジタルへの転換が遅れており、競合に差をつけられていた。",
    strategy: "広告・SEO・SNS三媒体を一元管理し、各施策の連携を強化。旅行需要に合わせた季節訴求を徹底。",
    result: "大幅改善",
    kpi: "ソーシャル 358%成長",
    period: "2021年10月〜",
    tags: ["SNS", "旅行", "デジタルマーケ", "総合支援", "フォロワー成長"],
    created_at: "2021-10-01",
  },
  {
    id: "c18",
    title: "ホテルチェーンWebサイトリニューアルで売上増加（東急不動産）",
    client_name: "東急不動産株式会社",
    industry: "不動産",
    services: ["Web制作"],
    summary: "商業施設サイトリニューアルにより売上増加を実現した。",
    background: "旧サイトはUI/UXが時代遅れで離脱率が高く、オンライン経由の売上が伸び悩んでいた。",
    strategy: "ユーザー調査に基づいたUI設計・商品導線の最適化・スマートフォン対応の抜本的改善を実施。",
    result: "改善",
    kpi: "売上増加",
    period: "2023年〜",
    tags: ["Web制作", "リニューアル", "不動産", "商業施設"],
    created_at: "2023-02-01",
  },

  // ── LLMO・AI ──────────────────────────────────────────
  {
    id: "c19",
    title: "LLMO（AI言及率最適化）でChatGPT・Gemini・Claudeへの言及率改善",
    client_name: "SBI損害保険",
    industry: "金融・保険",
    services: ["LLMO/AIO"],
    summary: "LLM言及率最適化（LLMO）施策でChatGPT・Gemini・Claude等AIの回答での言及率を改善。AI Overview対策も実施。",
    background: "AIの台頭によりユーザーの情報収集行動が変化し、AIに推薦されないと機会損失が発生。",
    strategy: "Forté.AIを活用したLLMO分析・自社コンテンツのAI学習データへの最適化・被引用構造の改善。",
    result: "改善",
    kpi: "ChatGPT/Gemini/Claude言及率改善",
    period: "2025年7月〜",
    tags: ["LLMO", "AI Overview", "ChatGPT", "Gemini", "金融", "Forté.AI"],
    created_at: "2025-07-01",
  },

  // ── リサーチ・調査 ────────────────────────────────────
  {
    id: "c20",
    title: "中古車買取チェーンのSEO流入減・CV減の原因をWebアンケートで特定",
    client_name: "アップルオートネットワーク（267店舗）",
    industry: "自動車",
    services: ["調査・リサーチ"],
    summary: "全国4,000人のWebアンケート調査によりSEOセッション22%減・CV18%減の原因を特定し改善施策を立案した。",
    background: "SEOとCV数が同時に悪化しており、原因が不明のまま施策を打てない状態だった。",
    strategy: "全国6エリア割付のWebアンケート（n=4,000）設計・実施・分析。ユーザー行動・競合比較軸を調査。",
    result: "改善",
    kpi: "原因特定・改善ロードマップ策定",
    period: "2025年8月〜",
    tags: ["調査", "アンケート", "自動車", "SEO", "CV改善", "原因特定"],
    created_at: "2025-08-01",
  },
  {
    id: "c21",
    title: "写真スタジオの顧客戦略調査でROI試算約400%・継続顧客化戦略を策定",
    client_name: "らかんスタジオ（フォトスタジオ）",
    industry: "その他",
    services: ["調査・リサーチ"],
    summary: "グループインタビュー・Webアンケート・1ON1調査によりマタニティ〜誕生日の継続顧客化戦略を策定。24ヶ月ROI試算ベース約400%。",
    background: "少子化対応として既存顧客のLTV向上・継続来店化が急務だった。",
    strategy: "定性・定量調査を組み合わせてカスタマージャーニーを可視化。LTV最大化施策を設計。",
    result: "大幅改善",
    kpi: "24ヶ月ROI試算 ベース約400%",
    period: "2023年〜",
    tags: ["調査", "LTV", "フォトスタジオ", "継続顧客化", "ROI"],
    created_at: "2023-04-01",
  },
];
